/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestPageImport } from './routes/testPage'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TestPageRoute = TestPageImport.update({
  id: '/testPage',
  path: '/testPage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/testPage': {
      id: '/testPage'
      path: '/testPage'
      fullPath: '/testPage'
      preLoaderRoute: typeof TestPageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testPage': typeof TestPageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testPage': typeof TestPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/testPage': typeof TestPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/testPage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/testPage'
  id: '__root__' | '/' | '/testPage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestPageRoute: typeof TestPageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestPageRoute: TestPageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/testPage"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/testPage": {
      "filePath": "testPage.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
